export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED";
export const INIT_INGREDIENTS = "INIT_INGREDIENTS";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";

export const PURCHASE_MALA_START = "PURCHASE_MALA_START";
export const PURCHASE_MALA_SUCCESS = "PURCHASE_MALA_SUCCESS";
export const PURCHASE_MALA_FAILED = "PURCHASE_MALA_FAILED";
export const INIT_PURCHASE = "INIT_PURCHASE";
export const FETCH_ORDERS_START = "FETCH_ORDERS_START";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAILED = "FETCH_ORDERS_FAILED";